website:
  title: "Mise en production"
  navbar:
    title: false
    background: "#447099"
    search: true
    align: center
    collapse-below: lg
    left:
      - href: https://ensae-reproductibilite.github.io/
        text: Mise en production
      - href: chapters/introduction.qmd
        text: Introduction
      - text: Les bases
        menu:
          - href: chapters/linux101.qmd
            text: Linux 101
          - href: chapters/git.qmd
            text: Git
      - text: Bonnes pratiques de développement
        menu:
          - href: chapters/code-quality.qmd
            text: Qualité du code
          - href: chapters/projects-architecture.qmd
            text: Structure des projets
          - href: chapters/big-data.qmd
            text: Traitement des données volumineuses
          - href: chapters/portability.qmd
            text: Portabilité
      - text: Mise en production
        menu:
          - href: chapters/yaml101.qmd
            text: YAML 101
          - href: chapters/deployment.qmd
            text: Déploiement
          - href: chapters/mlops.qmd
            text: MLOps
      - href: chapters/application.qmd
        text: Application
      - text: Projets
        menu:
          - href: chapters/evaluation.qmd
            text: Modalités d'évaluation
          - href: chapters/galerie.qmd
            text: Galerie des projets passés
      - icon: github
        menu:
          - text: Site web
            url:  https://github.com/ensae-reproductibilite/website
          - text: Slides
            url:  https://github.com/ensae-reproductibilite/slides
          - text: Application fil rouge
            url:  https://github.com/ensae-reproductibilite/application
